import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/ThemeProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import clsx from "clsx";

const playfairDisplay = Playfair_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(playfairDisplay.className, "relative min-h-screen")}
      >
        <Providers>
          <Header />
          {children}
          <Footer />
          <div className="absolute opacity-0  inset-0 -z-50 max-h-screen dark:opacity-100 background-gradient"></div>
          <div className="absolute pointer-events-none inset-0 -z-40 h-full bg-[url('/noisetexture.jpg')] opacity-0 mix-blend-soft-light dark:opacity-20 "></div>
        </Providers>
      </body>
    </html>
  );
}
