// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  hero: dynamic(() => import("./Hero")),
  techlist: dynamic(() => import("./Techlist")),
  toggle_theme_button: dynamic(() => import("./ToggleThemeButton")),
};
