// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  toggle_theme_button: dynamic(() => import("./ToggleThemeButton")),
};
