// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  content_index: dynamic(() => import("./ContentIndex")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  techlist: dynamic(() => import("./Techlist")),
  text_block: dynamic(() => import("./TextBlock")),
  toggle_theme_button: dynamic(() => import("./ToggleThemeButton")),
};
